### ISSUE TITLE
Play the mouse click sound on the whole website?

### ISSUE THREAD

**Issue by techflashYT** [techflashYT/My-Website#11]
I'm thinking use the same code that I used in .games/.my-game/.basicpage.php where it plays a _click_ sound when you click the mouse, and have that be a toggleable option throughout the entire website, and use cookies to tell wether it's on or off.

**Comment by sanikdah** [comment]
Never answered

**Comment by techflashYT** [comment]
After site redesign, the mouse click sound no longer exists, removed.
