### ISSUE TITLE
Ping the discord bot when an error occurs.

### ISSUE THREAD

**Issue by techflashYT** [techflashYT/My-Website#9]
Make a new discord bot that will be notified when an error occurs, and mention the ping the owner bot 5 times, I will make it so that mentioning the bot will cause the same 5 pings as before, just it'll repeat that process 5 times.

**Comment by sanikdah** [comment]
Still never fixed.

**Comment by techflashYT** [comment]
Discord bot can't react ot a ping so this won't work.
